
import React, { useMemo, useState } from 'react';
import { AuditLog, Part, User } from '../types';
import { shareReportAsFile, printView, shareToWhatsApp } from '../services/exportService';

interface Props {
  logs: AuditLog[];
  parts: Part[];
  currentUser: User;
}

const ReportsScreen: React.FC<Props> = ({ logs, parts, currentUser }) => {
  const analytics = useMemo(() => {
    const totalAssetValue = parts.reduce((sum, p) => sum + (p.onHand * (p.mav || 0)), 0);
    return {
      totalAssetValue,
      totalSKUs: parts.length,
      activityTotal: logs.length,
      variances: logs.filter(l => l.physicalQty !== l.onHandQty).length
    };
  }, [parts, logs]);

  const generateWorkToken = () => {
    const token = btoa(JSON.stringify({ 
      logs: logs.filter(l => l.userName === currentUser.name),
      time: new Date().toLocaleString(),
      userName: currentUser.name
    }));
    shareToWhatsApp(`🚨 *WORK REPORT: ${currentUser.name}* 🚨\n\nI have completed ${logs.length} audits. Paste this token in the Manage panel to merge my data.\n\n*Token:*\n${token}`);
  };

  const handleWhatsAppSummary = () => {
    const message = `📊 *INVENTORY SUMMARY*\n\nItems: ${analytics.totalSKUs}\nValue: ₹${analytics.totalAssetValue.toLocaleString()}\nTotal Audits: ${analytics.activityTotal}\nVariances: ${analytics.variances}\n\n_Generated by Tracker_`;
    shareToWhatsApp(message);
  };

  return (
    <div className="p-6 space-y-10 pb-28">
      <div className="space-y-2">
        <h2 className="text-4xl font-black text-coffee-900 tracking-tighter">Reports</h2>
        <p className="text-[10px] text-coffee-600 font-black uppercase tracking-[0.2em]">Operational Insights</p>
      </div>

      <div className="grad-primary p-10 rounded-[3.5rem] text-white shadow-2xl relative overflow-hidden">
        <p className="text-[11px] font-black uppercase tracking-[0.25em] opacity-80 mb-3">Total Asset Value</p>
        <p className="text-5xl font-black">₹{analytics.totalAssetValue.toLocaleString()}</p>
        <div className="mt-8 flex gap-3">
          <button onClick={handleWhatsAppSummary} className="flex-1 bg-emerald-600 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl">WhatsApp Summary</button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-5 no-print">
        <button onClick={() => shareReportAsFile('excel', logs, 'Inventory_Report')} className="grad-warm text-white py-6 rounded-[2.2rem] font-black text-[10px] uppercase tracking-widest shadow-xl">Export Excel</button>
        <button onClick={generateWorkToken} className="grad-royal text-white py-6 rounded-[2.2rem] font-black text-[10px] uppercase tracking-widest shadow-xl">Share Work Token</button>
      </div>

      <div className="premium-card rounded-[3.8rem] overflow-hidden border border-coffee-100 shadow-2xl">
        <div className="px-10 py-9 grad-primary text-white flex justify-between items-center">
          <h3 className="text-[11px] font-black uppercase tracking-[0.3em]">Activity Ledger</h3>
          <div className="px-5 py-2 bg-white/15 rounded-full text-[10px] font-black">{logs.length} Ops</div>
        </div>
        <div className="max-h-[500px] overflow-y-auto">
          <table className="w-full text-left text-[11px]">
            <tbody className="divide-y divide-coffee-50">
              {logs.map((log) => (
                <tr key={log.id} className="hover:bg-coffee-50">
                  <td className="px-10 py-7">
                    <p className="font-black text-coffee-900 text-sm leading-none mb-1.5">{log.partNumber}</p>
                    <p className="text-[9px] text-coffee-400 font-bold uppercase tracking-widest">By {log.userName} • {log.dateTime.split(',')[0]}</p>
                  </td>
                  <td className="px-10 py-7 text-right">
                    <span className={`px-4 py-2 rounded-full text-[9px] font-black uppercase tracking-widest ${log.physicalQty !== log.onHandQty ? 'bg-orange-50 text-orange-600' : 'bg-emerald-50 text-emerald-600'}`}>
                      {log.physicalQty !== log.onHandQty ? 'Variance' : 'OK'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsScreen;
