
import React, { useMemo } from 'react';
import { AuditLog, Part, User } from '../types';
import { shareReportAsFile, shareToWhatsApp } from '../services/exportService';

interface Props {
  logs: AuditLog[];
  parts: Part[];
  currentUser: User;
}

const ReportsScreen: React.FC<Props> = ({ logs, parts, currentUser }) => {
  const analytics = useMemo(() => {
    const totalAssetValue = parts.reduce((sum, p) => sum + (p.onHand * (p.mav || 0)), 0);
    return {
      totalAssetValue,
      totalSKUs: parts.length,
      activityTotal: logs.length,
      variances: logs.filter(l => l.physicalQty !== l.onHandQty).length
    };
  }, [parts, logs]);

  const handleWhatsAppSummary = () => {
    const message = `📊 *INVENTORY SUMMARY*\n\nItems: ${analytics.totalSKUs}\nValue: ₹${analytics.totalAssetValue.toLocaleString()}\nTotal Audits: ${analytics.activityTotal}\nVariances: ${analytics.variances}\n\n_Generated by Tracker_`;
    shareToWhatsApp(message);
  };

  const handleShareExcelToWhatsApp = async () => {
    if (logs.length === 0) {
      alert("No activity logs available to share.");
      return;
    }
    
    const fileName = `Inventory_Report_${currentUser.name}_${new Date().getTime()}`;
    const shareText = `Attached is the inventory report generated by ${currentUser.name}.`;
    
    // Using the native share sheet which allows selecting WhatsApp to send the actual FILE
    await shareReportAsFile('excel', logs, fileName, undefined, shareText);
  };

  return (
    <div className="p-6 space-y-10 pb-28">
      <div className="space-y-2">
        <h2 className="text-4xl font-black text-coffee-900 tracking-tighter">Reports</h2>
        <p className="text-[10px] text-coffee-600 font-black uppercase tracking-[0.2em]">Operational Insights</p>
      </div>

      <div className="grad-primary p-10 rounded-[3.5rem] text-white shadow-2xl relative overflow-hidden">
        <p className="text-[11px] font-black uppercase tracking-[0.25em] opacity-80 mb-3">Total Asset Value</p>
        <p className="text-5xl font-black">₹{analytics.totalAssetValue.toLocaleString()}</p>
        <div className="mt-8 flex gap-3">
          <button onClick={handleWhatsAppSummary} className="flex-1 bg-emerald-600 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl">Quick Text Summary</button>
        </div>
      </div>

      <div className="no-print">
        <button 
          onClick={handleShareExcelToWhatsApp} 
          className="w-full grad-royal text-white py-7 rounded-[2.5rem] font-black text-[11px] uppercase tracking-[0.3em] shadow-2xl flex items-center justify-center gap-3 active:scale-95 transition-all"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" className="mb-0.5"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
          Share in WhatsApp
        </button>
      </div>

      <div className="premium-card rounded-[3.8rem] overflow-hidden border border-coffee-100 shadow-2xl">
        <div className="px-10 py-9 grad-primary text-white flex justify-between items-center">
          <h3 className="text-[11px] font-black uppercase tracking-[0.3em]">Activity Ledger</h3>
          <div className="px-5 py-2 bg-white/15 rounded-full text-[10px] font-black">{logs.length} Ops</div>
        </div>
        <div className="max-h-[500px] overflow-y-auto">
          <table className="w-full text-left text-[11px]">
            <tbody className="divide-y divide-coffee-50">
              {logs.map((log) => (
                <tr key={log.id} className="hover:bg-coffee-50">
                  <td className="px-10 py-7">
                    <p className="font-black text-coffee-900 text-sm leading-none mb-1.5">{log.partNumber}</p>
                    <p className="text-[9px] text-coffee-400 font-bold uppercase tracking-widest">By {log.userName} • {log.dateTime.split(',')[0]}</p>
                  </td>
                  <td className="px-10 py-7 text-right">
                    <span className={`px-4 py-2 rounded-full text-[9px] font-black uppercase tracking-widest ${log.physicalQty !== log.onHandQty ? 'bg-orange-50 text-orange-600' : 'bg-emerald-50 text-emerald-600'}`}>
                      {log.physicalQty !== log.onHandQty ? 'Variance' : 'OK'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsScreen;
